services:
  - type: web
    name: node-app
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    branch: master
    envVars:
      - key: DATABASE_URL
        value: your-database-url
